### Get All Tasks
GET http://localhost/list-view

### Get Completed Tasks
GET http://localhost/list-view/complete

### Get Incomplete Tasks
GET http://localhost/list-view/incomplete

### Create Task
POST http://localhost/list-edit/add
Content-Type: application/json

{
  "desc": "Task 2",
  "state": false
}

### Delete Task
DELETE http://localhost/list-edit/delete/2

### Edit Task
PUT http://localhost/list-edit/edit/0
Content-Type: application/json

{
  "desc": "Edited",
  "state": true
}